In [1]:
from google.colab import files

uploaded = files.upload()

Saving textwin_sensor_dataset.csv to textwin_sensor_dataset.csv

In [2]:
import pandas as pd

df = pd.read_csv("textwin_sensor_dataset.csv")

df.head()

,Machine_ID,Temperature,Vibration,RPM,Humidity,Power,Running_Hours,Status
0,LOOM0001,35.84,0.54,1197,58.98,4.34,102,Running
1,LOOM0002,36.06,1.84,1185,60.36,4.23,97,Running
2,LOOM0003,33.31,1.26,1181,60.24,4.92,409,Running
3,LOOM0004,35.27,0.83,1217,59.11,5.07,438,Running
4,LOOM0005,36.83,1.55,1201,59.11,4.42,440,Running

In [3]:
df.shape

(5000, 8)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Machine_ID     5000 non-null   object
 1   Temperature    5000 non-null   float64
 2   Vibration      5000 non-null   float64
 3   RPM            5000 non-null   int64
 4   Humidity       5000 non-null   float64
 5   Power          5000 non-null   float64
 6   Running_Hours  5000 non-null   int64
 7   Status         5000 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 312.6+ KB

df["Status"].value_counts()

> Add blockquote

In [6]:
df["Status"].value_counts()

Status
Running        2000
Maintenance    1500
Critical       1000
Stopped         500
Name: count, dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df["Status"] = encoder.fit_transform(df["Status"])

df.head()

,Machine_ID,Temperature,Vibration,RPM,Humidity,Power,Running_Hours,Status
0,LOOM0001,35.84,0.54,1197,58.98,4.34,102,2
1,LOOM0002,36.06,1.84,1185,60.36,4.23,97,2
2,LOOM0003,33.31,1.26,1181,60.24,4.92,409,2
3,LOOM0004,35.27,0.83,1217,59.11,5.07,438,2
4,LOOM0005,36.83,1.55,1201,59.11,4.42,440,2

In [8]:
import joblib

joblib.dump(encoder, "label_encoder.pkl")

['label_encoder.pkl']

In [9]:
X = df.drop(columns=["Machine_ID","Status"])

y = df["Status"]

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [12]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=300,
    random_state=42
)

model.fit(X_train,y_train)

RandomForestClassifier(n_estimators=300, random_state=42)

prediction = model.predict(X_test)

In [14]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test,prediction)

print("Accuracy:",accuracy)

Accuracy: 1.0

from sklearn.metrics import classification_report

print(classification_report(y_test,prediction))

In [16]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,prediction)

array([[200,   0,   0,   0],
       [  0, 300,   0,   0],
       [  0,   0, 400,   0],
       [  0,   0,   0, 100]])

In [17]:
importance = pd.DataFrame({
    "Feature":X.columns,
    "Importance":model.feature_importances_
})

importance.sort_values(
    by="Importance",
    ascending=False
)

         Feature  Importance
1      Vibration    0.201209
0    Temperature    0.190177
5  Running_Hours    0.180197
3       Humidity    0.178322
2            RPM    0.134955
4          Power    0.115140

In [18]:
joblib.dump(model,"tmhp_model.pkl")

['tmhp_model.pkl']

In [19]:
files.download("tmhp_model.pkl")

In [20]:
files.download("label_encoder.pkl")